# Generated by Django 2.2.8 on 2019-12-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enceinte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostname',
            name='code',
        ),
        migrations.AlterField(
            model_name='hostname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
